import random
subjects = [
    "Shah Rukh Khan",
    "Narendra Modi",
    "Elon Musk",
    "Rahul Gandhi",
    "Mamata Banerjee",
    "Salman Khan",
    "Hrithik Roshan",
    "Mukesh Ambani",
    "Ratan Tata",
    "Virat Kohli",
    "MS Dhoni" ,
    "Sachin Tendulkar",
    "Cristiano Ronaldo",
    "Lionel Messi",
    "Bill Gates",
    "Mark Zuckerberg",
    "Sundar Pichai",
    "Jeff Bezos",
    "Tridip Samanta",
    "A college student",
    "A programmer ",
    "A teacher ",
    "A doctor",
    "A police officer",
    "A farmer",
    "A businessman",
    "A YouTuber",
    "A gamer",
    "A hacker",
    "An engineer",
    "A scientist",
    "A cricketer",
    "A footballer",
    "A dancer",
    "A singer",
    "A painter",
    "A traveler",
    "A chef",
    "A photographer"
]

actions = [
    "is spotted",
    "is riding a bike",
    "is riding a horse",
    "is swimming",
    "is running",
    "is cooking food",
    "is eating pizza",
    "is drinking coffee",
    "is writing code",
    "is reading a book",
    "is watching a movie",
    "is playing cricket",
    "is playing football",
    "is singing a song",
    "is dancing",
    "is drawing a picture",
    "is clicking photos",
    "is recording a video",
    "is driving a car",
    "is shopping",
    "is studying",
    "is teaching students",
    "is giving a speech",
    "is building a robot",
    "is fixing a laptop",
    "is flying a drone",
    "is riding a scooter",
    "is walking slowly",
    "is jogging",
    "is sleeping",
    "is meditating",
    "is exercising",
    "is lifting weights",
    "is learning Python",
    "is learning AI",
    "is playing games",
    "is coding a website"
]

objects = [
    "near Howrah Bridge",
    "in front of Delhi Gate",
    "inside a polluted pond",
    "in a village",
    "in Sundarban",
    "on a mountain",
    "at the beach",
    "inside a classroom",
    "in a computer lab",
    "at home",
    "inside a gym",
    "at a restaurant",
    "in a shopping mall",
    "at a railway station",
    "at the airport",
    "inside a bus",
    "on the road",
    "in a park",
    "inside a library",
    "on a playground",
    "in a stadium",
    "inside an office",
    "in a hospital",
    "inside a cinema hall",
    "on a rooftop",
    "beside a river",
    "under a tree",
    "near a temple",
    "near a mosque",
    "near a church",
    "in a village market",
    "inside a cafe",
    "on a bridge",
    "inside a hostel",
    "at a hotel",
    "on a highway",
    "inside a forest",
    "at a tourist spot"
]

while True:
    sms = input('Do you want to generate a headline (yes/no) :) ').lower()
    if sms=='yes':
       sentence = f"{random.choice(subjects)} {random.choice(actions)} {random.choice(objects)}."
       print('\n                                               Breaking News : ',sentence,'\n')
    else:
        print('Ok thanks :) Bye ')
        break
